package View;

public enum CommandType {
    SET_DATE ,
    ADD_BAEBAND ,
    STATUS_BARBAND ,
    STATUS_COW ,
    ADD_COW ,
    ADD_TANK ,
    STATUS_FARM ,
    FEED_BARBAND ,
    STATUS_STORAGE ,
    STATUS_TANKS ,
    MILK_COW ,
    ADD_FOOD_TO_STORAGE ,
    SELL_MILK ,
    EMPTY_TANK ,
    BUTCHER_COW ,
    MOVE_COW ,
    SHOW_RANKS ,
    INCREASE_STORAGE_CAPACITY ,
    ADD_NEW_FOOD ,
    END_DAY ,
    FEED_TYPES ,
    END_FEED ,
    FEED_PROPERTIES ,
    END ,
    INVALID_COMMAND
}
