package Controller;

public enum ControllerRequestType {
    START, DO_NOTHING, INVALID_COMMAND, INVALID_DATE, SHOW_BARBAND, INVALID_BARBAND, SHOW_COW, INVALID_COW,
    THERE_IS_NOT_ENOUGH_SPACE, COW_ADDED, SHOW_FARM, SHOW_STORAGE, SHOW_TANK, COW_MILKED_SUCCESSFULLY,
    COW_HAS_NO_MILK, INVALID_TANK, INVALID_FOOD_NAME, THERE_IS_NOT_ENOUGH_MILK, MILK_SOLD_SUCCESSFULLY,
    BUTCHER_COW, MOVE_COW, THERE_IS_NOT_ENOUGH_SPACE_IN_BARBAND
}
